// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQwwN0HCUMV2gzpSYS0kveXXDWM1ZL68',
    appId: '1:128085830553:web:298fe292022a3f9dd84108',
    messagingSenderId: '128085830553',
    projectId: 'pinpong-6992c',
    authDomain: 'pinpong-6992c.firebaseapp.com',
    databaseURL: 'https://pinpong-6992c-default-rtdb.firebaseio.com',
    storageBucket: 'pinpong-6992c.appspot.com',
    measurementId: 'G-VK6VXLLEB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa695exstTg7h8pQlApptohBtQx7Y4DXs',
    appId: '1:128085830553:android:d1fbabfa72cb29aed84108',
    messagingSenderId: '128085830553',
    projectId: 'pinpong-6992c',
    databaseURL: 'https://pinpong-6992c-default-rtdb.firebaseio.com',
    storageBucket: 'pinpong-6992c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xI38vtuNVxYeXOOGViGMDGEhAeuo6JY',
    appId: '1:128085830553:ios:f1792560d54bdbf5d84108',
    messagingSenderId: '128085830553',
    projectId: 'pinpong-6992c',
    databaseURL: 'https://pinpong-6992c-default-rtdb.firebaseio.com',
    storageBucket: 'pinpong-6992c.appspot.com',
    iosBundleId: 'com.example.pinpong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6xI38vtuNVxYeXOOGViGMDGEhAeuo6JY',
    appId: '1:128085830553:ios:c65df27dcde85e5dd84108',
    messagingSenderId: '128085830553',
    projectId: 'pinpong-6992c',
    databaseURL: 'https://pinpong-6992c-default-rtdb.firebaseio.com',
    storageBucket: 'pinpong-6992c.appspot.com',
    iosBundleId: 'com.example.pinpong.RunnerTests',
  );
}
